version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  print_pipeline:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - print_pipeline_id

workflows:
  say-hello-workflow:
    jobs:
      - print_pipeline
      
