version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  print_pipeline:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - print_pipeline_id
  faile_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: exit 1
      - run:
         command: echo failllllled
         when: on_fail


workflows:
  say-hello-workflow:
    jobs:
      - print_pipeline
      - faile_job
      
